### PR TITLE
Ignore *.pyc files (in .gitignore)

### PR DESCRIPTION
**Pull request by foolip**
Because they aren't ignored, the w3ctestlib submodule in
web-platform-tests can look like it has changes, which is annoying.

### CODE REVIEW

**Comment by foolip** [comment]
@plinss, can you review this? And if submitting PRs here is OK, as in #1, can you change "Read-only git mirror" in the repo description?

**Comment by foolip** [comment]
Ping @plinss. Or @gsnedders, how do I get changes into this repo?

**Comment by plinss** [comment]
I added a .gitignore that covers the .hgignore contents (includes *.pyc). Sorry for missing this earlier.

**Comment by gsnedders** [comment]
We imported w3ctestlib into wpt, given it isn't used elsewhere, back in May. We can just archive this repo.

**Pull request closed without merging**
